name:                purescript-cst
version:             0.1.0.0
github:              "natefaubion/purescript-cst"
license:             BSD3
author:              "Nathan Faubion"
copyright:           "2019 Nathan Faubion"

extra-source-files:
- README.md

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-methods
- -Wredundant-constraints

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/natefaubion/purescript-cst#readme>

dependencies:
- base >= 4.7 && < 5
- purescript == 0.12.2
- prettyprinter == 1.2.1
- megaparsec == 7.0.4
- text
- mtl
- dlist
- deepseq
- criterion
- containers
- array
- pretty-simple
- Glob
- async
- scientific

library:
  source-dirs: src

executables:
  purescript-cst-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purescript-cst

tests:
  purescript-cst-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purescript-cst
    - bytestring
    - filepath
    - tasty
    - tasty-golden
